<?php

namespace Database\Seeders;

use App\Models\CategoryPost;
use App\Models\Post;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        User::factory(5)->create();
        Post::factory(100)->create();


        DB::table('categories')->insert([
            [ 'user_id'=>'1',
                'name'=>'Laravel',
                'slug'=>'laravel',
                'is_published'=>'1',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [ 'user_id'=>'1',
                'name'=>'Wordpress',
                'slug'=>'wordpress',
                'is_published'=>'1',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [ 'user_id'=>'1',
                'name'=>'Python',
                'slug'=>'python',
                'is_published'=>'1',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [ 'user_id'=>'1',
                'name'=>'Js',
                'slug'=>'js',
                'is_published'=>'1',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [ 'user_id'=>'1',
                'name'=>'Html',
                'slug'=>'html',
                'is_published'=>'1',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
        ]);

        CategoryPost::factory(100)->create();

        DB::table('roles')->insert([
            [
                'name'=>'master',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'admin',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'user',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],

        ]);
        DB::table('permissions')->insert([
            [
                'name'=>'create role',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'edit role',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'delete role',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'set admin',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'create user',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'edit user',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'delete user',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'active user',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'write post',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'edit post',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'delete post',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'write category',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'edit category',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'delete category',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'write page',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'edit page',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],
            [
                'name'=>'delete page',
                'guard_name'=>'web',
                'created_at'=>carbon::now(),
                'updated_at'=>carbon::now(),],

        ]);
        DB::table('role_has_permissions')->insert([
            [
                'role_id' => '1',
                'permission_id' => '1',
            ],
            [
                'role_id' => '1',
                'permission_id' => '2',
            ],
            [
                'role_id' => '1',
                'permission_id' => '3',
            ],
            [
                'role_id' => '1',
                'permission_id' => '4',
            ],
            [
                'role_id' => '1',
                'permission_id' => '5',
            ],
            [
                'role_id' => '1',
                'permission_id' => '6',
            ],
            [
                'role_id' => '1',
                'permission_id' => '7',
            ],
            [
                'role_id' => '1',
                'permission_id' => '8',
            ],
            [
                'role_id' => '1',
                'permission_id' => '9',
            ],
            [
                'role_id' => '1',
                'permission_id' => '10',
            ],
            [
                'role_id' => '1',
                'permission_id' => '11',
            ],
            [
                'role_id' => '1',
                'permission_id' => '12',
            ],
            [
                'role_id' => '1',
                'permission_id' => '13',
            ],
            [
                'role_id' => '1',
                'permission_id' => '14',
            ],
            [
                'role_id' => '1',
                'permission_id' => '15',
            ],
            [
                'role_id' => '1',
                'permission_id' => '16',
            ],
            [
                'role_id' => '1',
                'permission_id' => '17',
            ],

        ]);
        DB::table('model_has_roles')->insert([
            [
                'role_id' => '1',
                'model_type' => 'App\Models\User',
                'model_id'=>'1'
            ],
        ]);

        DB::table('site_details')->insert([
            [
                'site_name' => 'Site Name',
            ],
        ]);

        DB::table('provinces')->insert([
            ['name'=>'آذربایجان شرقی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'آذربایجان غربی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'اردبیل', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'اصفهان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'البرز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'ایلام', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'بوشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'تهران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'چهارمحال و بختیاری', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'خراسان جنوبی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'خراسان رضوی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'خراسان شمالی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'خوزستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'زنجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'سمنان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'سیستان و بلوچستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'فارس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'قزوین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'قم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'کردستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'کرمان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'کرمانشاه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'کهگیلویه و بویراحمد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'گلستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'گیلان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'لرستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'مازندران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'مرکزی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'هرمزگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'همدان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['name'=>'یزد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
        ]);
        DB::table('cities')->insert([
            ['province_id'=>'1', 'name'=>'اسکو', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'اهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'آذرشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'بستان‌آباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'بناب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'تبریز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'جلفا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'چاراویماق', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'خداآفرین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'سراب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'شبستر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'عجب‌شیر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'کلیبر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'مراغه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'مرند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'ملکان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'میانه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'ورزقان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'هریس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'1', 'name'=>'هشترود', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'ارومیه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'اشنویه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'بوکان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'پلدشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'پیرانشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'تکاب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'چالدران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'چایپاره', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'خوی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'سردشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'سلماس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'شاهین‌دژ', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'شوط', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'ماکو', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'مهاباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'میاندوآب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'2', 'name'=>'نقده', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'اردبیل', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'انگوت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'بیله‌سوار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'پارس‌آباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'خلخال', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'سرعین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'کوثر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'گرمی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'مشگین‌شهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'نمین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'3', 'name'=>'نیر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'اردستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'اصفهان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'آران و بیدگل', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'برخوار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'بوئین و میاندشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'تیران و کرون', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'چادگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'خمینی‌شهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'خوانسار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'خور و بیابانک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'دهاقان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'سمیرم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'شاهین‌شهر و میمه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'شهرضا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'فریدن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'فریدون‌شهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'فلاورجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'کاشان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'گلپایگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'لنجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'مبارکه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'نائین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'نجف‌آباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'4', 'name'=>'نطنز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'5', 'name'=>'اشتهارد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'5', 'name'=>'ساوجبلاغ', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'5', 'name'=>'چهارباغ', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'5', 'name'=>'طالقان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'5', 'name'=>'فردیس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'5', 'name'=>'کرج', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'5', 'name'=>'نظرآباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'ایلام', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'ایوان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'آبدانان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'بدره', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'چرداول', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'چوار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'دره‌شهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'دهلران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'سیروان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'ملکشاهی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'مهران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'6', 'name'=>'هلیلان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'بوشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'تنگستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'جم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'دشتستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'دشتی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'دیر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'دیلم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'عسلویه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'کنگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'7', 'name'=>'گناوه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'اسلامشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'بهارستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'پاکدشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'پردیس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'پیشوا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'تهران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'دماوند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'رباط‌کریم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'ری', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'شمیرانات', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'شهریار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'فیروزکوه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'قدس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'قرچک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'ملارد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'8', 'name'=>'ورامین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'9', 'name'=>'اردل', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'9', 'name'=>'بروجن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'9', 'name'=>'بن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'9', 'name'=>'سامان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'9', 'name'=>'شهرکرد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'9', 'name'=>'فارسان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'9', 'name'=>'کوهرنگ', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'9', 'name'=>'کیار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'9', 'name'=>'لردگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'بشرویه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'بیرجند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'خوسف', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'درمیان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'زیرکوه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'سرایان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'سربیشه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'طبس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'فردوس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'قائنات', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'10', 'name'=>'نهبندان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'باخرز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'بجستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'بردسکن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'بینالود', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'تایباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'تربت جام', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'تربت حیدریه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'جغتای', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'جوین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'چناران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'خلیل‌آباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'خواف', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'خوشاب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'داورزن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'درگز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'رشتخوار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'زاوه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'زیرخان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'سبزوار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'سرخس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'ششتمد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'فریمان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'فیروزه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'قوچان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'کاشمر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'کلات', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'کوهسرخ', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'گلبهار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'گناباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'مشهد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'مه‌ولات', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'11', 'name'=>'نیشابور', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'12', 'name'=>'اسفراین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'12', 'name'=>'بجنورد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'12', 'name'=>'جاجرم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'12', 'name'=>'راز و جرگلان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'12', 'name'=>'شیروان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'12', 'name'=>'فاروج', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'12', 'name'=>'گرمه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'12', 'name'=>'مانه و سملقان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'امیدیه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'اندیکا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'اندیمشک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'اهواز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'ایذه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'آبادان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'آغاجاری', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'باغ‌ملک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'باوی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'بندر ماهشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'بهبهان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'حمیدیه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'خرمشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'دزفول', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'دشت آزادگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'رامشیر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'رامهرمز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'شادگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'شوش', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'شوشتر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'کارون', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'کرخه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'گتوند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'لالی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'مسجدسلیمان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'هفتکل', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'هندیجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'13', 'name'=>'هویزه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'14', 'name'=>'ابهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'14', 'name'=>'ایجرود', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'14', 'name'=>'خدابنده', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'14', 'name'=>'خرمدره', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'14', 'name'=>'زنجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'14', 'name'=>'سلطانیه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'14', 'name'=>'طارم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'14', 'name'=>'ماه‌نشان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'15', 'name'=>'آرادان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'15', 'name'=>'دامغان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'15', 'name'=>'سرخه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'15', 'name'=>'سمنان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'15', 'name'=>'شاهرود', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'15', 'name'=>'گرمسار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'15', 'name'=>'مهدی‌شهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'15', 'name'=>'میامی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'ایرانشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'تفتان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'چابهار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'خاش', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'دشتیاری', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'دلگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'راسک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'زابل', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'زاهدان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'زهک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'سراوان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'سرباز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'سیب و سوران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'فنوج', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'قصرقند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'کنارک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'گلشن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'مهرستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'میرجاوه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'نیک شهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'نیمروز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'هامون', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'16', 'name'=>'هیرمند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'ارسنجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'استهبان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'اقلید', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'اوز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'آباده', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'بوانات', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'بیضا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'پاسارگاد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'پختگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'جهرم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'خرامه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'خرم‌بید', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'خفر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'خنج', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'داراب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'رستم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'زرقان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'زرین‌دشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'سپیدان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'سرچهان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'سروستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'شیراز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'فراشبند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'فسا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'فیروزآباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'قیر و کارزین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'کازرون', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'کوار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'کوه چنار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'گراش', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'لارستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'لامرد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'مرودشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'ممسنی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'مهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'17', 'name'=>'نی ریز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'18', 'name'=>'البرز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'18', 'name'=>'آبیک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'18', 'name'=>'آوج', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'18', 'name'=>'بوئین‌زهرا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'18', 'name'=>'تاکستان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'18', 'name'=>'قزوین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'19', 'name'=>'قم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'بانه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'بیجار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'دهگلان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'دیواندره', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'سروآباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'سقز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'سنندج', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'قروه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'کامیاران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'20', 'name'=>'مریوان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'ارزوئیه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'انار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'بافت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'بردسیر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'بم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'جیرفت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'رابر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'راور', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'رفسنجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'رودبار جنوب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'ریگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'زرند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'سیرجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'شهربابک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'عنبرآباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'فاریاب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'فهرج', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'قلعه گنج', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'کرمان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'کوهبنان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'کهنوج', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'منوجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'21', 'name'=>'نرماشیر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'اسلام‌آباد غرب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'پاوه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'ثلاث باباجانی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'جوانرود', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'دالاهو', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'روانسر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'سرپل ذهاب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'سنقر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'صحنه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'قصرشیرین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'کرمانشاه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'کنگاور', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'گیلانغرب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'22', 'name'=>'هرسین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'23', 'name'=>'باشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'23', 'name'=>'بویراحمد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'23', 'name'=>'بهمئی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'23', 'name'=>'چرام', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'23', 'name'=>'دنا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'23', 'name'=>'کهگیلویه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'23', 'name'=>'گچساران', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'23', 'name'=>'لنده', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'23', 'name'=>'مارگون', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'آزادشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'آق‌قلا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'بندر گز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'ترکمن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'رامیان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'علی‌آباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'کردکوی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'کلاله', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'گالیکش', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'گرگان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'گمیشان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'گنبد کاووس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'مراوه‌تپه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'24', 'name'=>'مینودشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'املش', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'آستارا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'آستانه اشرفیه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'بندر انزلی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'تالش', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'خمام', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'رشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'رضوانشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'رودبار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'رودسر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'سیاهکل', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'شفت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'صومعه‌سرا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'فومن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'لاهیجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'لنگرود', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'25', 'name'=>'ماسال', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'ازنا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'الیگودرز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'بروجرد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'پلدختر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'خرم‌آباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'دلفان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'دورود', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'دوره', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'رومشکان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'سلسله', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'26', 'name'=>'کوهدشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'آمل', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'بابل', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'بابلسر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'بهشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'تنکابن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'جویبار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'چالوس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'رامسر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'ساری', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'سوادکوه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'سوادکوه شمالی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'سیمرغ', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'عباس‌آباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'فریدونکنار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'قائم‌شهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'کلاردشت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'گلوگاه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'محمودآباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'میاندرود', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'نکا', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'نور', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'27', 'name'=>'نوشهر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'اراک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'آشتیان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'تفرش', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'خمین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'خنداب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'دلیجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'زرندیه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'ساوه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'شازند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'فراهان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'کمیجان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'28', 'name'=>'محلات', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'ابوموسی', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'بستک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'بشاگرد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'بندر لنگه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'بندرعباس', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'پارسیان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'جاسک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'حاجی‌آباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'خمیر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'رودان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'سیریک', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'قشم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'29', 'name'=>'میناب', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'30', 'name'=>'اسدآباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'30', 'name'=>'بهار', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'30', 'name'=>'تویسرکان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'30', 'name'=>'رزن', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'30', 'name'=>'فامنین', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'30', 'name'=>'کبودرآهنگ', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'30', 'name'=>'ملایر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'30', 'name'=>'نهاوند', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'30', 'name'=>'همدان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'ابرکوه', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'اردکان', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'اشکذر', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'بافق', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'بهاباد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'تفت', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'خاتم', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'مهریز', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'میبد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
            ['province_id'=>'31', 'name'=>'یزد', 'created_at'=>carbon::now(), 'updated_at'=>carbon::now(),],
        ]);

    }

}
